name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Update setiap tengah malam UTC
  workflow_dispatch: # Bisa juga dijalankan manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: rizkyxp
          outputs: dist/github-contribution-grid-snake.svg
      - name: Push the Snake SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
